import { Printer, Table2 } from 'lucide-react'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { csvNum, csvRow, downloadCsv } from '../../csv'
import { CardHeading, selectCls } from '../../components/ui'
import { useStore } from '../../store'
import type { CompetencySetKey, GradingRecord } from '../../types'
import {
  MIN_GRADES,
  MIN_SESSIONS,
  PERIODS,
  REVIEW,
  WATCH,
  type Flag,
  type PeriodKey,
  periodLabel,
  scopeRecords,
  statsBySet,
} from '../../gradingStats'
import { formatDateTime } from '../Grading'

/**
 * Standardisierungsbericht nach ORA.ATO.110: Bewertet ein Instruktor
 * systematisch strenger oder milder als der Rest der Flotte? Genau diese
 * Frage muss eine ATO in der Standardisierungsbesprechung beantworten, und
 * genau dafür lag die Grundlage bisher nur roh in der Statistik.
 *
 * Der Bericht ist ein Dokument für die Behörde und deshalb — wie die
 * Formulare — durchgehend englisch, unabhängig von der Bediensprache.
 */

const fmt = (v: number | null, digits = 2) => (v === null ? '–' : v.toFixed(digits))
const fmtPct = (v: number | null) => (v === null ? '–' : `${v.toFixed(0)} %`)
const fmtDelta = (v: number | null) => (v === null ? '–' : `${v > 0 ? '+' : ''}${v.toFixed(2)}`)

export function StandardisationReport({
  records,
  setOfRecord,
  fleet,
  onFleetChange,
  fleetOptions,
  authority,
  onAuthorityChange,
  period,
  onPeriodChange,
}: {
  records: GradingRecord[]
  setOfRecord: (r: GradingRecord) => CompetencySetKey | null
  fleet: string
  onFleetChange: (v: string) => void
  fleetOptions: string[]
  authority: '' | 'AT' | 'UK'
  onAuthorityChange: (v: '' | 'AT' | 'UK') => void
  /** Flotte und Zeitraum liegen im Elternteil: Kalibrierungs-Kachel und
   *  Bericht müssen denselben Ausschnitt zeigen, sonst widersprechen sie
   *  einander wieder. */
  period: PeriodKey
  onPeriodChange: (p: PeriodKey) => void
}) {
  // Der Bericht ist ein Behördendokument: Sein gesamter Text kommt aus dem
  // Namensraum `forms`, den es nur auf Englisch gibt (siehe i18n/index.ts).
  const { t } = useTranslation()
  const { state, currentUser } = useStore()

  const doc = state.settings.documentHeader
  // Kennung passend zur gewählten Behörde; ohne Auswahl die AT-Nummer
  const approval = authority === 'UK' ? doc.approvalNumberUK || 'GBR.ATO.0541' : doc.approvalNumber
  const g = state.settings.grading
  const now = Date.now() + state.timeOffsetMs

  const scoped = useMemo(() => scopeRecords(records, { fleet, authority, period, now }), [records, fleet, authority, period, now])

  const sets = useMemo(
    () =>
      statsBySet(scoped, setOfRecord).map((s2) => ({
        ...s2,
        name: g.competencySets.find((c) => c.key === s2.key)?.name ?? s2.key,
        rows: s2.rows.map((r) => ({ ...r, name: state.users.find((u) => u.id === r.id)?.name ?? r.id })),
      })),
    [scoped, setOfRecord, state.users, g.competencySets],
  )

  const label = periodLabel(period)

  const exportCsv = () => {
    const row = csvRow
    let csv = row(['Instructor Connect — Standardisation Report'])
    csv += row([doc.atoName, approval])
    csv += row(['Period', label, 'Fleet', fleet || 'All fleets', 'Authority', authority || 'All authorities'])
    csv += row(['Generated', formatDateTime(now), 'Generated by', currentUser!.name])
    csv += row(['Thresholds', `watch >= ${WATCH.toFixed(2)}`, `review >= ${REVIEW.toFixed(2)}`, `min ${MIN_GRADES} grades / ${MIN_SESSIONS} sessions`])
    csv += row([])
    sets.forEach((s) => {
      csv += row([`Competency set: ${s.name}`])
      csv += row([
        'Instructor', 'Sessions', 'Grades', 'Mean', 'DeviationFromFleetMean',
        'Grade1', 'Grade2', 'Grade3', 'Grade4', 'Grade5', 'NotObserved',
        'ShareGrade1or2Pct', 'ShareGrade4or5Pct', 'NotCompetentRatePct', 'Assessment',
      ])
      s.rows.forEach((r) => {
        csv += row([
          r.name, r.sessions, r.n, csvNum(r.mean), csvNum(r.delta),
          r.dist['1'], r.dist['2'], r.dist['3'], r.dist['4'], r.dist['5'], r.dist.NO,
          csvNum(r.lowShare), csvNum(r.highShare), csvNum(r.ncRate), t(`forms:std.flag.${r.flag}`),
        ])
      })
      csv += row([
        'Fleet mean', s.sessions, s.n, csvNum(s.overall), '',
        '', '', '', '', '', '',
        csvNum(s.lowShare), csvNum(s.highShare), csvNum(s.ncRate), '',
      ])
      csv += row([])
    })
    const d = new Date(now)
    const stamp = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
    downloadCsv(`standardisation-report_${stamp}.csv`, csv)
  }

  const flagCls: Record<Flag, string> = {
    none: 'text-dim',
    watch: 'font-semibold text-warm',
    review: 'font-semibold text-danger',
    insufficient: 'text-dim',
  }

  return (
    <div className="space-y-3 print-landscape">
      {/* Bedienelemente in der Bediensprache — sie stehen nicht auf dem Papier */}
      <div className="flex flex-wrap items-center gap-2 print:hidden">
        <select value={fleet} onChange={(e) => onFleetChange(e.target.value)} className={`${selectCls} w-auto`}>
          <option value="">{t('forms:admin.allAircraft')}</option>
          {fleetOptions.map((f) => (
            <option key={f} value={f}>
              {f}
            </option>
          ))}
        </select>
        <select value={authority} onChange={(e) => onAuthorityChange(e.target.value as '' | 'AT' | 'UK')} className={`${selectCls} w-auto`}>
          <option value="">{t('forms:admin.allAuthorities')}</option>
          <option value="AT">{t('forms:authorityAT', { nr: doc.approvalNumber || 'AT.ATO.106' })}</option>
          <option value="UK">{t('forms:authorityUK', { nr: doc.approvalNumberUK || 'GBR.ATO.0541' })}</option>
        </select>
        <select value={period} onChange={(e) => onPeriodChange(e.target.value as PeriodKey)} className={`${selectCls} w-auto`}>
          {PERIODS.map((p) => (
            <option key={p.key} value={p.key}>
              {t(`forms:std.period.${p.key}`)}
            </option>
          ))}
        </select>
        <button
          onClick={() => window.print()}
          className="min-h-11 flex items-center gap-1.5 rounded-xl border border-line/15 px-3 text-[13px] transition hover:bg-line/5"
        >
          <Printer size={15} /> {t('forms:print')}
        </button>
        <button
          onClick={exportCsv}
          className="min-h-11 flex items-center gap-1.5 rounded-xl border border-line/15 px-3 text-[13px] transition hover:bg-line/5"
          disabled={sets.length === 0}
        >
          <Table2 size={15} /> {t('forms:std.exportCsv')}
        </button>
      </div>

      {/* Kopf des Dokuments: ohne ATO, Zeitraum und Flotte ist ein Ausdruck
          nicht zuordenbar — genau daran scheitern Audits. */}
      <div className="border-b-2 border-line/60 pb-2">
        <p className="text-[12px] font-semibold uppercase tracking-wide">
          {[doc.atoName, approval].filter(Boolean).join(' · ')}
        </p>
        <h2 className="text-[19px] font-bold tracking-tight">{t('forms:std.title')}</h2>
        <p className="mt-1 flex flex-wrap justify-between gap-x-4 gap-y-0.5 text-[12px] text-dim">
          <span>
            {t('forms:std.period.label')}: {label} · {t('forms:admin.fleet')}: {fleet || t('forms:admin.allAircraft')} · {t('forms:admin.authority')}: {approval || t('forms:admin.allAuthorities')}
          </span>
          <span>{t('forms:exportStamp', { date: formatDateTime(now), name: currentUser!.name })}</span>
        </p>
      </div>

      {sets.length === 0 && <p className="pt-4 text-center text-sm text-dim">{t('forms:empty')}</p>}

      {sets.map((s) => (
        <div key={s.key} className="rounded-2xl border border-line/10 bg-surface/60 p-3.5">
          <CardHeading className="mb-2">
            {t('forms:std.set')}: <span className="text-ink">{s.name}</span>
          </CardHeading>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-[12px]">
              <thead>
                <tr className="border-b border-line/20 text-left text-dim">
                  <th className="py-1.5 pr-2 font-medium">{t('forms:std.instructor')}</th>
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.sessionsCol')}</th>
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.gradesCol')}</th>
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.meanCol')}</th>
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.deltaCol')}</th>
                  {['1', '2', '3', '4', '5', 'NO'].map((k) => (
                    <th key={k} className="py-1.5 pr-2 text-right font-medium">
                      {k}
                    </th>
                  ))}
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.lowCol')}</th>
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.highCol')}</th>
                  <th className="py-1.5 pr-2 text-right font-medium">{t('forms:std.ncCol')}</th>
                  <th className="py-1.5 font-medium">{t('forms:std.assessmentCol')}</th>
                </tr>
              </thead>
              <tbody>
                {s.rows.map((r) => (
                  <tr key={r.id} className="border-b border-line/10">
                    <td className="py-1.5 pr-2 font-medium">{r.name}</td>
                    <td className="py-1.5 pr-2 text-right tabular-nums">{r.sessions}</td>
                    <td className="py-1.5 pr-2 text-right tabular-nums">{r.n}</td>
                    <td className="py-1.5 pr-2 text-right tabular-nums">{fmt(r.mean)}</td>
                    <td className={`py-1.5 pr-2 text-right tabular-nums ${flagCls[r.flag]}`}>{fmtDelta(r.delta)}</td>
                    {['1', '2', '3', '4', '5', 'NO'].map((k) => (
                      <td key={k} className="py-1.5 pr-2 text-right tabular-nums text-dim">
                        {r.dist[k] || '–'}
                      </td>
                    ))}
                    <td className="py-1.5 pr-2 text-right tabular-nums">{fmtPct(r.lowShare)}</td>
                    <td className="py-1.5 pr-2 text-right tabular-nums">{fmtPct(r.highShare)}</td>
                    <td className="py-1.5 pr-2 text-right tabular-nums">{fmtPct(r.ncRate)}</td>
                    <td className={`py-1.5 ${flagCls[r.flag]}`}>{t(`forms:std.flag.${r.flag}`)}</td>
                  </tr>
                ))}
                <tr className="border-t-2 border-line/30 font-semibold">
                  <td className="py-1.5 pr-2">{t('forms:std.fleetMean')}</td>
                  <td className="py-1.5 pr-2 text-right tabular-nums">{s.sessions}</td>
                  <td className="py-1.5 pr-2 text-right tabular-nums">{s.n}</td>
                  <td className="py-1.5 pr-2 text-right tabular-nums">{fmt(s.overall)}</td>
                  <td className="py-1.5 pr-2 text-right tabular-nums">—</td>
                  {['1', '2', '3', '4', '5', 'NO'].map((k) => (
                    <td key={k} className="py-1.5 pr-2" />
                  ))}
                  <td className="py-1.5 pr-2 text-right tabular-nums">{fmtPct(s.lowShare)}</td>
                  <td className="py-1.5 pr-2 text-right tabular-nums">{fmtPct(s.highShare)}</td>
                  <td className="py-1.5 pr-2 text-right tabular-nums">{fmtPct(s.ncRate)}</td>
                  <td />
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      ))}

      {sets.length > 0 && (
        <p className="text-[12px] leading-relaxed text-dim">
          {t('forms:std.footnote', { watch: WATCH.toFixed(2), review: REVIEW.toFixed(2), grades: MIN_GRADES, sessions: MIN_SESSIONS })}
        </p>
      )}
    </div>
  )
}
